const { Worker } = require("bullmq");
const IORedis = require("ioredis");
const mongoose = require("mongoose");
const axios = require("axios");

// Redis connection
const connection = new IORedis({
  host: process.env.REDIS_HOST,
  port: 6379,
  maxRetriesPerRequest: null,
});

// Mongo connection
mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("Mongo connected in worker"))
  .catch((err) => console.error(err));

// Schema
const PRSchema = new mongoose.Schema(
  {
    repo: { type: String, required: true },
    prNumber: { type: Number, required: true },
    action: String,
    title: String,
    author: String,
    aiReview: String,
    riskScore: Number,
    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true },
);

PRSchema.index({ repo: 1, prNumber: 1 }, { unique: true });

const PR = mongoose.model("PullRequest", PRSchema);

// Fetch PR diff from GitHub
async function fetchPRDiff(repo, prNumber) {
  const response = await axios.get(
    `https://api.github.com/repos/${repo}/pulls/${prNumber}`,
    {
      headers: {
        Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        Accept: "application/vnd.github.v3.diff",
      },
    },
  );

  return response.data;
}

async function postCommentToPR(repo, prNumber, aiText, riskScore) {
  try {
    const commentBody = `
## 🧠 NeuroOps AI DevOps Review

**Risk Score:** ${riskScore}/10

---

${aiText}

---

_This review was automatically generated by NeuroOps AI Copilot._
`;

    await axios.post(
      `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`,
      {
        body: commentBody,
      },
      {
        headers: {
          Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
          Accept: "application/vnd.github+json",
        },
      },
    );

    console.log("Posted AI review comment to GitHub PR");
  } catch (error) {
    console.error(
      "Failed to post PR comment:",
      error.response?.data || error.message,
    );
  }
}

// Worker
const worker = new Worker(
  "pr-review-queue",
  async (job) => {
    console.log("Processing PR job:", job.data);

    try {
      // 1️⃣ Fetch real diff
      const diff = await fetchPRDiff(job.data.repo, job.data.prNumber);

      // 2️⃣ Truncate large diffs (prevent huge prompt)
      const truncatedDiff = diff.slice(0, 8000);

      // 3️⃣ Build AI prompt using real diff
      const prompt = `
You are an expert DevOps code reviewer.

Review the following GitHub Pull Request diff:

${truncatedDiff}

Provide:
1. Short summary of changes
2. Potential bugs
3. Security risks
4. Performance concerns
5. Risk score from 1 to 10

Be short, concise, technical, and structured.
`;

      // 4️⃣ Call Ollama
      const response = await axios.post(
        process.env.OLLAMA_URL + "/api/generate",
        {
          model: "deepseek-coder:6.7b",
          prompt,
          stream: false,
          options: {
            num_predict: 700,
            temperature: 0.2,
            top_p: 0.9,
          },
        },
      );

      const aiText = response.data.response;

      // 5️⃣ Extract risk score more safely
      let riskScore = 5;
      const scoreMatch = aiText.match(/Risk score.*?(\b([1-9]|10)\b)/i);
      if (scoreMatch) {
        riskScore = parseInt(scoreMatch[1]);
      }

      // 6️⃣ Save to Mongo
      // await PR.create({
      //   ...job.data,
      //   aiReview: aiText,
      //   riskScore,
      // });

      await PR.findOneAndUpdate(
        {
          repo: job.data.repo,
          prNumber: job.data.prNumber,
        },
        {
          ...job.data,
          aiReview: aiText,
          riskScore,
        },
        {
          upsert: true,
          new: true,
          setDefaultsOnInsert: true,
        },
      );

      await postCommentToPR(
        job.data.repo,
        job.data.prNumber,
        aiText,
        riskScore,
      );

      console.log("Saved PR with AI diff review to Mongo");
    } catch (error) {
      console.error("Error processing PR job:", error.message);
      throw error;
    }
  },
  { connection },
);

// Logging
worker.on("completed", (job) => {
  console.log(`Job ${job.id} completed successfully`);
});

worker.on("failed", (job, err) => {
  console.error(`Job ${job?.id} failed:`, err.message);
});

worker.on("error", (err) => {
  console.error("Worker encountered an error:", err.message);
});
